name: Build and Deploy Docs

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  docs:
    uses: bobleesj/release-scripts/.github/workflows/_publish-docs-on-release.yml@v3.13
    with:
      project: diffpy.snmf
      c_extension: false
