name: Build and Deploy Docs

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish-docs-on-release:
    uses: Billingegroup/release-scripts/.github/workflows/_publish-docs-on-release.yml@v0
    with:
      project: diffpy.snmf
      c_extension: false
