name: Tests on PR

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    uses: bobleesj/release-scripts/.github/workflows/_tests-on-pr.yml@3.13
    with:
      project: diffpy.snmf
      c_extension: false
      headless: false
